### PR TITLE
Overhaul save consistency, especially player saves

### LINKED ISSUE #1031: Players losing personal saves
*Version:* Unstable, probably since ~2.2 at least

*Mods:* Probably doesn't matter.

*Environment*: MP dedi, maybe other MP

***Issue:***
Players sometimes lose their rank and money on load. Loadouts are still loaded. Not sure about personal garage yet. Being (one of?) the first players to connect may be a risk factor. Not easily replicable.

In this issue, the load player command is correctly sent to the server, and apparently the data is found in the server's profilenamespace. It's not yet clear whether the data has been correctly saved in the first place.

This is distinct from save loss caused by the player changing UID or saving/disconnecting while in the wrong body (latter should be fixed now).

### LINKED ISSUE #1185: Autosaves are spamming excess player saves
*Version:* Unstable

*Mods:* Any

*Environment*: Any MP

***Issue:***
Fixed the map-board save, forgot to check this one. Duh.

### LINKED ISSUE #1198: Player saves on disconnect losing data
*Version:* Unstable, probably older

*Mods:* ACE + RHS, not sure if important

*Environment*: MP dedi + HC

***Issue:***
No replication case yet, but there are enough community-server incidents to confirm that there's a problem. Disconnecting (using "abort") often causes players to be saved with zero money and no loadout, as if the player unit changed during the disconnect/save process. Not yet sure how this happens, but it's possible that there's no reasonable workaround and the player save concept needs a general rethink.

### PR DESCRIPTION
**Pull request by jaj22**
## What type of PR is this.
1. [X] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
- Fixes bug where player saves wouldn't load correctly due to multiple global setVariables.
- Fixes bug where player saving could be enabled slightly before their stats were loaded.
- Fixes bug where autosave would spam additional player saves.
- Fixes minor exploit where players could gain money by not loading their previous game.
- Fixes issue where autosave wouldn't trigger unless there was a commander on the server.
- Fixes bug where player loadout wasn't loaded in SP.
- Works around unknown-cause issue where player unit lacked variables on disconnection.
- Adds some save/load logging to diagnose future broken player saves.

The first bug needed a substantial reorganisation so that the global variables related to the player save are always set globally from the server on startup. There's now a resetPlayer function which handles the case of selecting "no" to load previous session. This function sets the player money to the minimum of 100 and the player's previous money, which removes the need for setting the startup money to 95.

### Please specify which Issue this PR Resolves.
closes #1185
closes #1031
maybe closes #1198

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in singleplayer?
2. [X] Have you loaded the mission in LAN host?
3. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Too dangerous to merge without serious testing, especially savePlayer as it's called directly from saveLoop, so if it has any persistent bugs then saves may be blocked in general.

### How can the changes be tested?
Get a server with a bunch of players on it. Have them repeatedly disconnect and reconnect by various methods while using the manual and autosaves heavily. Saves while remote controlling or unconscious should be tested. Make sure there are no script errors logged, and that no-one loses money/rank/garage/loadout inappropriately.

### CODE REVIEW

File: A3-Antistasi/dialogs.hpp [hunk 1]
```diff
@@ -981,7 +981,7 @@ class game_options 		{
 			w = 0.175015 * safezoneW;
 			h = 0.0560125 * safezoneH;
 			tooltip = "Use this option to save your current game. It does save the most important data in a ""Grand Theft Auto"" way. This opnion allows good MP save and independent saves of any version update. Vanilla saves are disabled because of lack of several features";
-			action = "closeDialog 0;if (player == theBoss) then {[] remoteExecCall [""A3A_fnc_saveLoop"", 2, false];} else {[] remoteExecCall [""A3A_fnc_saveLoop"", player, false]; hintC ""Personal Stats Saved""};";
+			action = "closeDialog 0; [] spawn A3A_fnc_persistentSave;";
```
Comment (MeltedPixel) [inline A3-Antistasi/dialogs.hpp:984]: This looks good, however we eliminate the notification to let users that Stat's have been saved. Is this as per design?

Comment (jaj22) [reply A3-Antistasi/dialogs.hpp:984]: The hintC got moved to persistentSave, and seems to work (you can test it in hosted by making yourself ineligible). Could be moved to the fancy hint for interface consistency though.
