### PR TITLE
Fix conflicting addon messages from aircraft loadout configs

### LINKED ISSUE #3314: [Bug]: Aircraft loadout configs have identical patch names
Doesn't seem to cause a problem but should be fixed. Maybe use a patch name macro like in config_fixes.

### PR DESCRIPTION
**Pull request by jaj22**
### What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
The aircraft loadout configs all had the same CfgPatches name as core (A3A_core), which caused RPT errors. Not sure it did anything else important, but it should be cleaned up.   

### Please specify which Issue this PR Resolves.
closes #3314

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### CODE REVIEW

**Review by Tiny-DM — APPROVED** [review]
Adding another line to `script_component.hpp`....lgtm

File: A3A/addons/core/Templates/AircraftLoadouts/config.cpp [hunk 1]
```diff
@@ -1,7 +1,7 @@
 #include "..\..\script_component.hpp"
 
 class CfgPatches {
-    class ADDON {
+    class PATCHNAME(AirLoadout_defaults) {
```
Comment (ante185) [inline A3A/addons/core/Templates/AircraftLoadouts/config.cpp:4]:
```suggestion
    class PATCHNAME(AirLoadout_BASE) {
```

**Review by ante185 — APPROVED** [review]
looks good to me

File: A3A/addons/core/Templates/AircraftLoadouts/config.cpp (hunk 1 above)
Comment (jaj22) [reply A3A/addons/core/Templates/AircraftLoadouts/config.cpp:4]: I'm actually inclined to delete that file and remove the inheritance because it doesn't do anything. getText and getArray return `""` and `[]` as default values anyway.

Comment (killerswin2) [reply A3A/addons/core/Templates/AircraftLoadouts/config.cpp:4]: no one inherits from the defaults, so no need to name it base.

**Review by killerswin2 — APPROVED** [review]
